name: eixam_connect_ui
description: Reusable UI package for EIXAM Connect
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  eixam_connect_core:
    path: ../eixam_connect_core
